name: "Run Tests and Package"
on:
  push:
  pull_request: 
jobs:
  tests-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vs: ["57", "58", "latest"]
        py: ["39", "310"]
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: vs-engine
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#checks.x86_64-linux.check-python${{ matrix.py }}-vapoursynth${{ matrix.vs }}

  tests-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        vs: ["57", "58", "latest"]
        py: ["39", "310"]
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: vs-engine
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#checks.x86_64-darwin.check-python${{ matrix.py }}-vapoursynth${{ matrix.vs }}

  build:
    runs-on: ubuntu-latest
    needs: 
    - tests-linux
    - tests-darwin
    steps:
    # Set-up runner.
    - uses: actions/checkout@v2.4.0
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: vs-engine
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # Replace the dirty-tag with the commit-id.
    - if: "!(github.event_name == 'push' && contains(github.ref, 'refs/tags/'))"
      run: |
        cat pyproject.toml | sed 's/\(version = "\)\(.*\)+dirty\("\)/\1\2.dev0+${{ steps.vars.outputs.sha_short }}\3/g' > pyproject.toml.tagged
        cat pyproject.toml.tagged
        mv pyproject.toml.tagged pyproject.toml

    # Remove the dirty-tag from the builder.
    - if: "github.event_name == 'push' && contains(github.ref, 'refs/tags/')"
      run: |
        cat pyproject.toml | sed 's/\(version = "\)\(.*\)+dirty\("\)/\1\2\3/g' > pyproject.toml.tagged
        cat pyproject.toml.tagged
        mv pyproject.toml.tagged pyproject.toml

    # Build the distribution.
    - run: nix build -L .#dist
    - run: |
        mkdir dist
        cp result/* dist
        ls -lAh dist
    - name: Archive distribution
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: |
          dist/**/*

    # publish:
    #   runs-on: ubuntu-latest
    #   if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/')
    #   needs: build
    #   steps:
    #     - uses: actions/download-artifact@v3
    #       with:
    #         name: Packages
    #         path: dist
    #     - name: Publish distribution 📦 to Test PyPI
    #       uses: pypa/gh-action-pypi-publish@master
    #       with:
    #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #         repository_url: https://test.pypi.org/legacy/
