name: "Tasks"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vs: ["57", "latest"]
        py: ["39", "310"]
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: vs-engine
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#checks.x86_64-linux.py${{ matrix.py }}_vs${{ matrix.vs }}

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: vs-engine
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        cat pyproject.toml | sed 's/\(version = "\)\(.*\)\("\)/\1\2+${{ steps.vars.outputs.sha_short }}\3/g' > pyproject.toml.tagged
        mv pyproject.toml.tagged
    - run: nix build -L .#dist
    - run: |
        mkdir dist
        cp result/* dist
        ls -lAh dist
    - name: Archive distribution
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: |
          dist/**/*
