name: ""
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vs: ["57", "latest"]
        py: ["39", "310"]
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: vs-engine
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#checks.x86_64-linux.py${{ matrix.py }}_vs${{ matrix.vs }}
    - run: nix build -L .#dist
    - name: Archive distribution
      uses: actions/upload-artifact@v3
      with:
        name: Packages
        path: |
          result/**/*
